#!/usr/bin/env bash
set -euo pipefail

# scaffold-mission.sh — Create the full mission directory structure
# Usage: scaffold-mission.sh <mission_id> <working_directory>

if [ $# -lt 2 ]; then
  echo "Usage: scaffold-mission.sh <mission_id> <working_directory>" >&2
  exit 1
fi

MISSION_ID="$1"
WORKING_DIR="$2"
MISSION_DIR="$HOME/.gemini-mc/missions/mis_${MISSION_ID}"
NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Create mission directory and handoffs subdirectory
mkdir -p "${MISSION_DIR}/handoffs"

# state.json — initial mission state
cat > "${MISSION_DIR}/state.json" <<EOF
{
  "missionId": "mis_${MISSION_ID}",
  "state": "planning",
  "workingDirectory": "${WORKING_DIR}",
  "completedFeatures": 0,
  "totalFeatures": 0,
  "createdAt": "${NOW}",
  "updatedAt": "${NOW}",
  "sealedMilestones": [],
  "milestonesWithValidationPlanned": []
}
EOF

# features.json — empty features array
cat > "${MISSION_DIR}/features.json" <<EOF
{
  "features": []
}
EOF

# mission.md — empty template
cat > "${MISSION_DIR}/mission.md" <<EOF
# Mission Proposal

<!-- Mission description and plan will be generated by the planner -->
EOF

# validation-contract.md — empty template
cat > "${MISSION_DIR}/validation-contract.md" <<EOF
# Validation Contract

<!-- Behavioral assertions will be generated by the planner -->
EOF

# validation-state.json — empty assertions
cat > "${MISSION_DIR}/validation-state.json" <<EOF
{
  "assertions": {}
}
EOF

# progress_log.jsonl — empty event log
: > "${MISSION_DIR}/progress_log.jsonl"

# messages.jsonl — empty inter-agent messages
: > "${MISSION_DIR}/messages.jsonl"

# AGENTS.md — empty template
cat > "${MISSION_DIR}/AGENTS.md" <<EOF
# Agent Guidance

<!-- Worker guidance and mission boundaries will be defined by the planner -->
EOF

echo "Mission mis_${MISSION_ID} scaffolded at ${MISSION_DIR}"
