#!/usr/bin/env bash
set -euo pipefail

# scaffold-mission.sh — Create the full mission directory structure
# Usage: scaffold-mission.sh <mission_id> <working_directory>

if [ $# -lt 2 ]; then
  echo "Usage: scaffold-mission.sh <mission_id> <working_directory>" >&2
  exit 1
fi

MISSION_ID="$1"
WORKING_DIR="$2"
MISSION_DIR="$HOME/.gemini-mc/missions/mis_${MISSION_ID}"
NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Create mission directory and handoffs subdirectory
mkdir -p "${MISSION_DIR}/handoffs"

# Escape JSON strings (handle backslash and double-quote)
MID="mis_${MISSION_ID}"
MID="${MID//\\/\\\\}"; MID="${MID//\"/\\\"}"
WD="${WORKING_DIR//\\/\\\\}"; WD="${WD//\"/\\\"}"

# Write all files in a single subshell to reduce syscall overhead
{
  # state.json
  printf '{\n  "missionId": "%s",\n  "state": "planning",\n  "workingDirectory": "%s",\n  "completedFeatures": 0,\n  "totalFeatures": 0,\n  "createdAt": "%s",\n  "updatedAt": "%s",\n  "sealedMilestones": [],\n  "milestonesWithValidationPlanned": []\n}\n' \
    "$MID" "$WD" "$NOW" "$NOW" > "${MISSION_DIR}/state.json"

  # features.json
  printf '{\n  "features": []\n}\n' > "${MISSION_DIR}/features.json"

  # validation-state.json
  printf '{\n  "assertions": {}\n}\n' > "${MISSION_DIR}/validation-state.json"

  # mission.md
  printf '# Mission Proposal\n\n<!-- Mission description and plan will be generated by the planner -->\n' > "${MISSION_DIR}/mission.md"

  # validation-contract.md
  printf '# Validation Contract\n\n<!-- Behavioral assertions will be generated by the planner -->\n' > "${MISSION_DIR}/validation-contract.md"

  # AGENTS.md
  printf '# Agent Guidance\n\n<!-- Worker guidance and mission boundaries will be defined by the planner -->\n' > "${MISSION_DIR}/AGENTS.md"

  # Empty files
  : > "${MISSION_DIR}/progress_log.jsonl"
  : > "${MISSION_DIR}/messages.jsonl"
}

echo "Mission mis_${MISSION_ID} scaffolded at ${MISSION_DIR}"
